source 'https://github.com/tiki/PodspecRepo.git'

platform :ios, '14.0'

def capacitor_pods
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'Plugin' do
  capacitor_pods
  use_frameworks!
  
  pod 'TikiSdk'
end

target 'PluginTests' do
  capacitor_pods
end
