source 'https://github.com/tiki/PodspecRepo.git'

platform :ios, '13.0'

def capacitor_pods
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'Plugin' do
  capacitor_pods
  use_frameworks!
  
  pod 'TikiSdk', "~> 2.1.1"
end

target 'PluginTests' do
  capacitor_pods
end
