/*
 * Copyright (c) TIKI Inc.
 * MIT license. See LICENSE file in root directory.
 */

/**
 * Represents common tag values that can be associated with a
 * {@link TitleRecord}.
 */
export enum CommonTags {
  /**
   * Such as first or last name.
   */
  NAME = 'name',

  /**
   * Including but not limited to a hashed email address.
   */
  EMAIL_ADDRESS = 'email_address',

  /**
   * Including but not limited to a hashed phone number.
   */
  PHONE_NUMBER = 'phone_number',

  /**
   * Such as home address, physical address, or mailing address.
   */
  PHYSICAL_ADDRESS = 'physical_address',

  /**
   * Any other information that can be used to contact the user.
   */
  CONTACT_INFO = 'contact_info',

  /**
   * Health and medical data or health-related human subject research.
   */
  HEALTH = 'health',

  /**
   * Fitness and exercise data.
   */
  FITNESS = 'fitness',

  /**
   * Such as form of payment, payment card number, or bank account number.
   */
  PAYMENT_INFO = 'payment_info',

  /**
   * Such as credit score.
   */
  CREDIT_INFO = 'credit_info',

  /**
   * Such as salary, income, assets, debts, or any other financial information.
   */
  FINANCIAL_INFO = 'financial_info',

  /**
   * Information that describes the location of a user or device with the same
   * or greater resolution as a latitude and longitude with three or more
   * decimal places.
   */
  PRECISE_LOCATION = 'precise_location',

  /**
   * Information that describes the location of a user or device with lower
   * resolution than a latitude and longitude with three or more decimal
   * places.
   */
  COARSE_LOCATION = 'coarse_location',

  /**
   * Such as racial or ethnic data, sexual orientation, pregnancy or childbirth
   * information, disability, religious or philosophical beliefs, trade union
   * membership, political opinion, genetic information, or biometric data.
   */
  SENSITIVE_INFO = 'sensitive_info',

  /**
   * Such as a list of contacts in the user’s phone, address book, or social
   * graph.
   */
  CONTACTS = 'contacts',

  /**
   * Including subject line, sender, recipients, and contents of the email,
   * sms, or other text-based messages.
   */
  MESSAGES = 'messages',

  /**
   * The user’s photos or videos.
   */
  PHOTO_VIDEO = 'photo_video',

  /**
   * The user’s voice or sound recordings.
   */
  AUDIO = 'audio',

  /**
   * Such as saved games, multiplayer matching or gameplay logic, or
   * user-generated content in-game.
   */
  GAMEPLAY_CONTENT = 'gameplay_content',

  /**
   * Data generated by the user during a customer support request.
   */
  CUSTOMER_SUPPORT = 'customer_support',

  /**
   * Any other user-generated content.
   */
  USER_CONTENT = 'user_content',

  /**
   * Information about content the user has viewed that is not part of your
   * app, such as websites.
   */
  BROWSING_HISTORY = 'browsing_history',

  /**
   * Information about searches performed.
   */
  SEARCH_HISTORY = 'search_history',

  /**
   * Such as screen name, handle, account ID, assigned user ID, customer number,
   * or other user- or account-level ID that can be used to identify a
   * particular user or account.
   */
  USER_ID = 'user_id',

  /**
   * Such as the device’s advertising identifier, or other device-level ID.
   */
  DEVICE_ID = 'device_id',

  /**
   * An account’s or individual’s purchases or purchase tendencies.
   */
  PURCHASE_HISTORY = 'purchase_history',

  /**
   * Such as app launches, taps, clicks, scrolling information, music listening
   * data, video views, saved place in a game, video, or song, or other
   * information about how the user interacts with your app.
   */
  PRODUCT_INTERACTION = 'product_interaction',

  /**
   * Such as information about the advertisements the user has seen.
   */
  ADVERTISING_DATA = 'advertising_data',

  /**
   * Any other data about user activity in your app.
   */
  USAGE_DATA = 'usage_data',

  /**
   * Such as crash logs.
   */
  CRASH_DATA = 'crash_data',

  /**
   * Such as launch time, hang rate, or energy use.
   */
  PERFORMANCE_DATA = 'performance_data',

  /**
   * Any other data collected for the purposes of measuring technical
   * diagnostics related to your app.
   */
  DIAGNOSTIC_DATA = 'diagnostic_data',
}
